### PR TITLE
Add option base64 encoding

### PR DESCRIPTION
**Pull request by samiralibabic**

### CODE REVIEW

**Comment by shikiyoku** [comment]
Any updates on this?

**Comment by felipearosemena** [comment]
Any progress on this?

**Comment by sigorilla** [comment]
For what is this option? You can use `encode` and `transform`:

```js
require('postcss-inline-svg')({
    encode: (svg) => Buffer.from(svg).toString('base64'),
    transform: (encoded) => `"data:image/svg+xml;base64,${encoded}"`
})
```

**Comment by hudochenkov** [comment]
@sigorilla's solutions is good. Use if base64 encoding is needed.

**Pull request closed without merging**
