### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hudochenkov**
Separated from https://github.com/TrySound/postcss-inline-svg/pull/77.

### CODE REVIEW

**Comment by hudochenkov** [comment]
Travis doesn't report back to Github anymore ¯﻿\﻿_﻿(﻿ツ﻿)﻿_﻿/﻿¯ Here's the build https://travis-ci.org/github/TrySound/postcss-inline-svg/builds/739551559

**Comment by TrySound** [comment]
Weird, im ok to migrate. Never used actions before though.

**Comment by hudochenkov** [comment]
I've set it up in stylelint. Works great. Shall I do this in this PR or separate?

**Review by TrySound — APPROVED** [review]

**Comment by TrySound** [comment]
Separate please

**Pull request merged**
