### PR TITLE
Add support for multiple search paths option

### PR DESCRIPTION
**Pull request by ovidiusabou**
See #34

### CODE REVIEW

**Comment by TrySound** [comment]
Thanks. I will check out soon.

**Comment by Blindmikey** [comment]
Awesome work, can't wait to be using this.

**Comment by wmschram** [comment]
Do you have a ETA for when this awesome feature will be merged?

**Comment by zslabs** [comment]
Would love to see this in as well. A use-case for me would be building a base framework that has certain SVGs inlined, and then consuming that framework (and adding onto with other inline SVGs) within an actual project.

**Comment by zslabs** [comment]
I created [an npm package](https://www.npmjs.com/package/postcss-inline-svg-multipath) until this is merged in.

**Comment by hoffmeyer** [comment]
I would like this feature.
I will be using @zslabs package until this will hopefully be merged in at some point.

**Comment by hudochenkov** [comment]
Merged in https://github.com/TrySound/postcss-inline-svg/pull/53. We're going to release soon.

**Pull request closed without merging**
